name: Check Environments Existence

on:
  workflow_dispatch:
    inputs:
      token:
        description: "GitHub Token"
        required: true

jobs:
  check-environments:
    runs-on: ubuntu-latest

    steps:
      - name: Check Environments
        id: check
        run: |
          GITHUB_TOKEN=$1
          repo_owner=$(echo $GITHUB_REPOSITORY | cut -d'/' -f1)
          repo_name=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)

          # Check if Development environment exists
          development_status=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: token $GITHUB_TOKEN" \
            -X GET "https://api.github.com/repos/$repo_owner/$repo_name/environments/Development")

          # Check if Testing environment exists
          testing_status=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: token $GITHUB_TOKEN" \
            -X GET "https://api.github.com/repos/$repo_owner/$repo_name/environments/Testing")

          # Check if Production environment exists
          production_status=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: token $GITHUB_TOKEN" \
            -X GET "https://api.github.com/repos/$repo_owner/$repo_name/environments/Production")

          if [ $development_status -eq 200 ]; then
            echo "Development environment exists."
          else
            echo "Development environment does not exist."
          fi

          if [ $testing_status -eq 200 ]; then
            echo "Testing environment exists."
          else
            echo "Testing environment does not exist."
          fi

          if [ $production_status -eq 200 ]; then
            echo "Production environment exists."
          else
            echo "Production environment does not exist."
          fi

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
